# Generated by Django 5.2.7 on 2025-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_location_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', help_text='Current status of the event', max_length=50, verbose_name='Status'),
        ),
    ]
