# Generated by Django 5.2.7 on 2025-12-02 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_alter_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the invitation', max_length=20, verbose_name='Status')),
                ('event', models.ForeignKey(help_text='Event for which invitation was sent', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event', verbose_name='Event')),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_event_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('invited_user', models.ForeignKey(help_text='User who received the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited User')),
            ],
            options={
                'verbose_name': 'Event Invitation',
                'verbose_name_plural': 'Event Invitations',
                'db_table': 'event_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='event_invit_event_i_c3b3e1_idx'), models.Index(fields=['invited_user', 'status'], name='event_invit_invited_1495b8_idx'), models.Index(fields=['invited_by'], name='event_invit_invited_bcbf77_idx'), models.Index(fields=['status'], name='event_invit_status_1015ee_idx')],
                'unique_together': {('event', 'invited_user')},
            },
        ),
    ]
