# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('events', '0005_event_location'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the event venue', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(help_text='Categories this event belongs to', related_name='events', through='categories.EventCategory', to='categories.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City where the event takes place', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='geography.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the event takes place', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='geography.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_perm',
            field=models.CharField(choices=[('organizer', 'Organizer Only'), ('admins', 'Admins Only'), ('participants', 'All Participants')], default='participants', help_text='Who can invite others to this event', max_length=50, verbose_name='Invitation Permission'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Maximum number of participants (leave empty for unlimited)', null=True, verbose_name='Max Participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', help_text='Current status of the event', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='When the event will take place', verbose_name='Event Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Detailed event description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates if this record has been soft-deleted', verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='User who created and manages this event', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_date_e70fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'date'], name='events_status_ce8b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'date'], name='events_organiz_947637_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['country', 'city'], name='events_country_a212a8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_deleted', 'status'], name='events_is_dele_869370_idx'),
        ),
    ]
