# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', help_text='Current status of the friendship', max_length=20, verbose_name='Status')),
                ('receiver', models.ForeignKey(help_text='User who received the friendship request', on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(help_text='User who initiated the friendship request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='friendships_sender__25f76c_idx'), models.Index(fields=['receiver', 'status'], name='friendships_receive_c88b04_idx'), models.Index(fields=['status'], name='friendships_status_e57cb7_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
