# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_remove_event_location_remove_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record has been soft-deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('content', models.TextField(help_text='The comment text', verbose_name='Content')),
                ('event', models.ForeignKey(help_text='Event this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event', verbose_name='Event')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.eventcomment', verbose_name='Parent Comment')),
                ('user', models.ForeignKey(help_text='User who posted this comment', on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Comment',
                'verbose_name_plural': 'Event Comments',
                'db_table': 'event_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='event_comme_event_i_59a12d_idx'), models.Index(fields=['user'], name='event_comme_user_id_c35797_idx'), models.Index(fields=['parent'], name='event_comme_parent__e9d921_idx'), models.Index(fields=['created_at'], name='event_comme_created_e52a49_idx')],
            },
        ),
    ]
