# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Full name of the country', max_length=100, unique=True, verbose_name='Country Name')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='countries_code_df63e8_idx'), models.Index(fields=['name'], name='countries_name_19480f_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Name of the city', max_length=100, verbose_name='City Name')),
                ('country', models.ForeignKey(help_text='Country this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['country', 'name'],
                'indexes': [models.Index(fields=['name'], name='cities_name_a7bf2e_idx'), models.Index(fields=['country', 'name'], name='cities_country_dbe920_idx')],
                'unique_together': {('name', 'country')},
            },
        ),
    ]
