# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Human-readable name of the category', max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the category', max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='categories_slug_b4303a_idx'), models.Index(fields=['name'], name='categories_name_98d7d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('category', models.ForeignKey(help_text='Category assigned to the event', on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='categories.category', verbose_name='Category')),
                ('event', models.ForeignKey(help_text='Event being categorized', on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'db_table': 'event_categories',
                'ordering': ['event', 'category'],
                'indexes': [models.Index(fields=['event'], name='event_categ_event_i_e34079_idx'), models.Index(fields=['category'], name='event_categ_categor_b3f8cc_idx')],
                'unique_together': {('event', 'category')},
            },
        ),
    ]
