# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_remove_event_location_remove_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the participation', max_length=20, verbose_name='Status')),
                ('is_admin', models.BooleanField(default=False, help_text='Whether this user has admin privileges for the event', verbose_name='Is Admin')),
                ('event', models.ForeignKey(help_text='Event being participated in', on_delete=django.db.models.deletion.CASCADE, related_name='participants_rel', to='events.event', verbose_name='Event')),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who invited this participant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('user', models.ForeignKey(help_text='Participating user', on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
                'db_table': 'events_participants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_part_event_i_f43780_idx'), models.Index(fields=['user', 'status'], name='events_part_user_id_560308_idx'), models.Index(fields=['status'], name='events_part_status_4693d0_idx'), models.Index(fields=['invited_by'], name='events_part_invited_6bd4b6_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
