# Generated by Django 5.2.7 on 2025-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_eventparticipant_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventparticipant',
            name='events_part_invited_6bd4b6_idx',
        ),
        migrations.RemoveField(
            model_name='eventparticipant',
            name='invited_by',
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted')], default='accepted', help_text='Current status of the participation (always accepted)', max_length=20, verbose_name='Status'),
        ),
    ]
