# Generated by Django 5.2.7 on 2025-11-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_remove_event_location_remove_event_participants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record has been soft-deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('url', models.CharField(help_text='URL or path to the photo file', max_length=500, verbose_name='Photo URL')),
                ('caption', models.TextField(blank=True, help_text='Optional caption describing the photo', null=True, verbose_name='Caption')),
                ('is_cover', models.BooleanField(default=False, help_text='Whether this photo is the event cover image', verbose_name='Is Cover Photo')),
                ('event', models.ForeignKey(help_text='Event this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event', verbose_name='Event')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this photo', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'db_table': 'event_photos',
                'ordering': ['-is_cover', '-created_at'],
                'indexes': [models.Index(fields=['event', 'is_cover'], name='event_photo_event_i_ea9cb3_idx'), models.Index(fields=['uploaded_by'], name='event_photo_uploade_d5013a_idx'), models.Index(fields=['created_at'], name='event_photo_created_4ceda0_idx')],
            },
        ),
    ]
